version: "3"
services:
  food-delivery-config-server:
    container_name: food-delivery-config-server
    # deploy:
    #   replicas: 1
    #   resources:
    #     limits:
    #       cpus: '0.256'
    #       memory: 512M
    #     reservations:
    #       cpus: '0.128'
    #       memory: 128M
    image: 211125430268.dkr.ecr.ap-southeast-1.amazonaws.com/food-delivery-config-server:latest
    restart: always
    environment:
      PORT: 8888
      EUREKA_INSTANCE_HOSTNAME: discovery-service:88761
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://discovery-service:8761/eureka/
    ports:
      - 8888:8888
    networks:
      - food-delivery-net

  food-delivery-discovery-service:
      container_name: food-delivery-discovery-service
      # deploy:
      #   replicas: 1
      #   resources:
      #     limits:
      #       cpus: '0.256'
      #       memory: 512M
      #     reservations:
      #       cpus: '0.128'
      #       memory: 128M
      image: 211125430268.dkr.ecr.ap-southeast-1.amazonaws.com/food-delivery-discovery-service:latest
      restart: always
      environment:
        HOSTNAME: http://food-delivery-discovery-service:8761/eureka/
        EUREKA_INSTANCE_HOSTNAME: food-delivery-discovery-service
        SPRING_CONFIG_IMPORT: optional:configserver:http://food-delivery-config-server:8888
      ports:
        - 8761:8761
      networks:
        - food-delivery-net

  food-delivery-gateway-service:
    container_name: food-delivery-gateway-service
#    deploy:
#      replicas: 1
#      resources:
#        limits:
#          cpus: '0.256'
#          memory: 512M
#        reservations:
#          cpus: '0.128'
#          memory: 128M
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://food-delivery-config-server:8888
      EUREKA_INSTANCE_HOSTNAME: food-delivery-discovery-service:88761
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://food-delivery-discovery-service:8761/eureka/
      
    ports:
      - 8222:8222
    networks:
      - food-delivery-net
    depends_on:
      - food-delivery-discovery-service
      # - keycloak-ms

#   customer-service:
#     container_name: customer-service
# #    deploy:
# #      replicas: 1
# #      resources:
# #        limits:
# #          cpus: '0.256'
# #          memory: 512M
# #        reservations:
# #          cpus: '0.128'
# #          memory: 128M
#     build:
#       context: ./customer
#       dockerfile: Dockerfile
#     restart: always
#     environment:
#       MONGODB_URI: mongodb://user:1234@116.206.127.212:27017/admin
#       SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
#       EUREKA_INSTANCE_HOSTNAME: discovery-service:88761
#       EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://discovery-service:8761/eureka/
#       ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
#     ports:
#       - 8090:8090
#     networks:
#       - food-delivery-net
#     depends_on:
#       - discovery-service
#       - gateway-service
#       - zipkin
#   keycloak-ms:
#     container_name: keycloak-ms
#     image: quay.io/keycloak/keycloak:24.0.2
#     ports:
#       - 9098:8080
#     environment:
#       KEYCLOAK_ADMIN: admin
#       KEYCLOAK_ADMIN_PASSWORD: admin
#     networks:
#       - food-delivery-net
#     command:
#       - "start-dev"

#   zipkin:
#     container_name: zipkin
#     image: openzipkin/zipkin
#     ports:
#       - "9411:9411"
#     networks:
#       - food-delivery-net

networks:
  food-delivery-net:
    driver: bridge
