version: "3"
services:
  food-delivery-config-server:
    image: 211125430268.dkr.ecr.ap-southeast-1.amazonaws.com/food-delivery-config-server:latest
    container_name: food-delivery-config-server
    restart: always
    environment:
      PORT: 8888
      EUREKA_INSTANCE_HOSTNAME: discovery-service:88761
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://discovery-service:8761/eureka/
    ports:
      - 8888:8888
    networks:
      - food-delivery-net

  food-delivery-discovery-service:
    image: 211125430268.dkr.ecr.ap-southeast-1.amazonaws.com/food-delivery-discovery-service:latest
    container_name: food-delivery-discovery-service
    restart: always
    environment:
      HOSTNAME: http://food-delivery-discovery-service:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: food-delivery-discovery-service
      SPRING_CONFIG_IMPORT: optional:configserver:http://food-delivery-config-server:8888
    ports:
      - 8761:8761
    networks:
      - food-delivery-net

  food-delivery-gateway-service:
    image: 211125430268.dkr.ecr.ap-southeast-1.amazonaws.com/food-delivery-gateway-service:latest
    container_name: food-delivery-gateway-service
    restart: always
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://food-delivery-config-server:8888
      EUREKA_INSTANCE_HOSTNAME: food-delivery-discovery-service
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://food-delivery-discovery-service:8761/eureka/
    ports:
      - 8222:8222
    networks:
      - food-delivery-net
    depends_on:
      - food-delivery-discovery-service

  food-delivery-customer-service:
    image: 211125430268.dkr.ecr.ap-southeast-1.amazonaws.com/food-delivery-customer-service:latest
    container_name: food-delivery-customer-service
    restart: always
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://food-delivery-config-server:8888
      EUREKA_INSTANCE_HOSTNAME: food-delivery-discovery-service
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://food-delivery-discovery-service:8761/eureka/
    ports:
      - 8093:8093
    networks:
      - food-delivery-net
    depends_on:
      - food-delivery-discovery-service
      - food-delivery-gateway-service

  food-delivery-ordering-service:
    image: 211125430268.dkr.ecr.ap-southeast-1.amazonaws.com/food-delivery-ordering-service:latest
    container_name: food-delivery-ordering-service
    restart: always
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://food-delivery-config-server:8888
      EUREKA_INSTANCE_HOSTNAME: food-delivery-discovery-service
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://food-delivery-discovery-service:8761/eureka/
      CUSTOMER_URL: http://food-delivery-gateway-service:8222/api/v1/customer
      RIDER_URL: http://food-delivery-gateway-service:8222/api/v1/rider
      RESTAURANT_URL: http://food-delivery-gateway-service:8222/api/v1/restaurant
    ports:
      - 8091:8091
    networks:
      - food-delivery-net
    depends_on:
      - food-delivery-discovery-service
      - food-delivery-gateway-service

  food-delivery-rider-service:
    image: 211125430268.dkr.ecr.ap-southeast-1.amazonaws.com/food-delivery-rider-service:latest
    container_name: food-delivery-rider-service
    restart: always
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://food-delivery-config-server:8888
      EUREKA_INSTANCE_HOSTNAME: food-delivery-discovery-service
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://food-delivery-discovery-service:8761/eureka/
    ports:
      - 8092:8092
    networks:
      - food-delivery-net
    depends_on:
      - food-delivery-discovery-service
      - food-delivery-gateway-service

  food-delivery-restaurant-service:
    image: 211125430268.dkr.ecr.ap-southeast-1.amazonaws.com/food-delivery-restaurant-service:latest
    container_name: food-delivery-restaurant-service
    restart: always
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://food-delivery-config-server:8888
      EUREKA_INSTANCE_HOSTNAME: food-delivery-discovery-service
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://food-delivery-discovery-service:8761/eureka/
    ports:
      - 8094:8094
    networks:
      - food-delivery-net
    depends_on:
      - food-delivery-discovery-service
      - food-delivery-gateway-service

networks:
  food-delivery-net:
    driver: bridge